import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Rethink_Sans, Passions_Conflict, Inter } from "next/font/google";
import { ModeToggle } from "@/components/darkmode-toggle";
import "./globals.css";

const rethinkSans = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
});

const passionsConflict = Passions_Conflict({
  weight: "400",
  variable: "--font-passion-conflict",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${rethinkSans.variable} ${passionsConflict.variable} ${inter.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <div className="z-20 absolute top-0 end-0 pe-4 pt-4">
            <ModeToggle />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
